### ISSUE TITLE
`unsupported line` on lines without function offset

### ISSUE THREAD

**Issue by Kibouo** [Kazhuu/asm2cfg#1]
Hi! Was excited to try this script as it's quite hard to find alternatives.

I'm working with a stripped binary and function bounds are unknown. This means no function offsets in the shape of `<+number>`.

The script doesn't seem to like that. On the appended log it and bails with: `unsupported line: => 0x0000555555555faf:	push   rbp`.

[gdb.log](https://github.com/Kazhuu/asm2cfg/files/6070842/gdb.log)

**Comment by Kazhuu** [comment]
I actually decided to work on this and update this project to support stripped binaries as well. This also gave some me some other ideas. Thanks for posting the issue!

**Comment by Kazhuu** [comment]
I added support for stripped assembly and I took your log as part of the example in the repo. Thank you! Here you can see end result of your function: https://github.com/Kazhuu/asm2cfg/blob/main/0x555555555faf-0x555555557008.pdf.
