### ISSUE TITLE
"No function name"

### ISSUE THREAD

**Issue by Kibouo** [Kazhuu/asm2cfg#2]
I tried working around #1 by adding `<+0>` after every instruction, which at least circumvents that error.

However, as my disassembly dump is the result from an address range, it doesn't include the function name (stripped binary still).

The script exits with: `First line of the file does not contain a function name`.

**Comment by Kazhuu** [comment]
Yeah the script wasn't designed to work with dump like this when I created it. I wasn't working with stripped binary. That error you see is from the fact that python expects function name from the first line.

What I checked the log out it could be possible to add support for this kind of format. Just the jump line parsing needs some update and also it doesn't handle call instructions to outside of the function. Not sure how those would be modeled in CFG. Maybe just an arrow to the address pointed by the call instruction. How fluent you're with python want to give this a stab?

**Comment by Kazhuu** [comment]
I close this one in favor for the earlier issue #1 . Let's keep the issue focused.
