### ISSUE TITLE
What may lead to inconsistent outputs (when the binaries are compiled with different compiler versions)?

### ISSUE THREAD

**Issue by Hanseltu** [Kazhuu/asm2cfg#30]
Hi,

Thanks for your contribution to the fantastic tool! May I ask some questions for you when I tried to use your tool in my current research work?

I expect the tool could stably produce CFG with different binaries from the same source code but with varying compiler versions,  and I will further investigate the difference between those binaries. After running the tool for a couple of days, I found that in some cases, `asm2cfg` produces significantly different CFGs. I am not an expert on the binary world, and I guess I may wrongly use the tool. So, please fix me if I misunderstood something, thanks!

The following are simple experiments to explain what I want to convey. The source code `test.c` will be compiled with `gcc-11.1.0 -O1 test.c -o test1` to `test1` and with `gcc-trunk -O1 test.c -o test2` to `test2`. Then, I used the command recommended on the homepage to produce assembly code. Note that in `test.c`, I insert some 'markers' to represent different blocks and those `markers` should not be optimized away. Now, I present the commands I used to reproduce the experiment:

```
$objdump -d ./test1 | sed -ne '/<main/,/^$/p' > test1.asm
$objdump -d ./test2 | sed -ne '/<main/,/^$/p' > test2.asm
$grep marker test1.asm
   1262b:	e8 ad ff ff ff       	callq  125dd <marker_start>
   127ad:	e8 d7 e9 fe ff       	callq  1189 <marker_0>
   127e0:	e8 c7 39 ff ff       	callq  61ac <marker_567>
   127ff:	e8 7a 3a ff ff       	callq  627e <marker_573>
   12819:	e8 27 3c ff ff       	callq  6445 <marker_586>
   12832:	e8 77 3c ff ff       	callq  64ae <marker_589>
   12868:	e8 93 fd ff ff       	callq  12600 <marker_end>
$grep marker test2.asm
  40ccff:	e8 c0 ff ff ff       	callq  40ccc4 <marker_start>
  40ce81:	e8 c0 42 ff ff       	callq  401146 <marker_0>
  40cea0:	e8 4c 43 ff ff       	callq  4011f1 <marker_9>
  40cea5:	e8 5a 43 ff ff       	callq  401204 <marker_10>
  40cec9:	e8 a6 48 ff ff       	callq  401774 <marker_68>
  40cece:	e8 e9 48 ff ff       	callq  4017bc <marker_71>
  40ced3:	e8 2c 49 ff ff       	callq  401804 <marker_74>
  40ced8:	e8 df 48 ff ff       	callq  4017bc <marker_71>
  40cedd:	e8 22 49 ff ff       	callq  401804 <marker_74>
  40cee2:	e8 d5 48 ff ff       	callq  4017bc <marker_71>
  40cee7:	e8 18 49 ff ff       	callq  401804 <marker_74>
  40ceec:	e8 cb 48 ff ff       	callq  4017bc <marker_71>
  40cef1:	e8 0e 49 ff ff       	callq  401804 <marker_74>
  40cf55:	e8 fa 49 ff ff       	callq  401954 <marker_88>
  40cf5a:	e8 9d 4a ff ff       	callq  4019fc <marker_95>
  40cf5f:	e8 e0 4a ff ff       	callq  401a44 <marker_98>
  40cf7d:	e8 ba 76 ff ff       	callq  40463c <marker_567>
  40cfa0:	e8 27 77 ff ff       	callq  4046cc <marker_573>
  40cfca:	e8 c3 41 ff ff       	callq  401192 <marker_4>
  40cfea:	e8 3d 5f ff ff       	callq  402f2c <marker_321>
  40cfef:	e8 68 5f ff ff       	callq  402f5c <marker_323>
  40d026:	e8 49 5f ff ff       	callq  402f74 <marker_324>
  40d02b:	e8 74 5f ff ff       	callq  402fa4 <marker_326>
  40d06a:	e8 95 65 ff ff       	callq  403604 <marker_394>
  40d07e:	e8 b1 65 ff ff       	callq  403634 <marker_396>
  40d08d:	e8 02 66 ff ff       	callq  403694 <marker_400>
  40d0be:	e8 c1 66 ff ff       	callq  403784 <marker_410>
  40d116:	e8 89 67 ff ff       	callq  4038a4 <marker_422>
  40d155:	e8 c2 73 ff ff       	callq  40451c <marker_555>
  40d15f:	e8 a0 76 ff ff       	callq  404804 <marker_586>
  40d178:	e8 cf 76 ff ff       	callq  40484c <marker_589>
  40d1ae:	e8 29 fb ff ff       	callq  40ccdc <marker_end>
```

We could observe that the number of markers of the two versions of the assembly code differs a lot. Note that the marker in `test2.asm` but not in `test1.asm` does not mean those markers are optimized away. To say why I natively run the two binaries with input and here are the results:

```
$./test1  0 0x0 0x777700 0 0x7 0xa7 0x0 0 0 0 0x0 0x8 0xA 0x000 0xA
start04321323394396400410422555567573end
$./test2  0 0x0 0x777700 0 0x7 0xa7 0x0 0 0 0 0x0 0x8 0xA 0x000 0xA
start04321323394396400410422555567573end
```
The sequences `start04321323394396400410422555567573end` means `start 0 4 321 323 394 396 400 410 422 555 567 573 end`. We can see some markers (e.g., marker_4) are alive but they are not presented in the `test1.asm`.

I used the current master version of `asm2cfg` and the `gcc-trunk` version is `gcc version 13.0.0 20220528 (experimental) (GCC)`.

Here are some files I mentioned above to help reproduce in your machine (`test-E.c` is the source code preprocessed with `gcc -E test.c`).
[reproducer.zip](https://github.com/Kazhuu/asm2cfg/files/8798490/reproducer.zip)

What may be the reason why `test1.asm` lacks so much information? Is it possible for me to get the right results?

Thank you so much and looking forward to your response!

Best regards,
Haoxin

**Comment by Kazhuu** [comment]
Hello and thank you! I'm not so familiar with GCC internals, more with LLVM. I originally started this tool for my research as well on LLVM. 

I would highly suggest that different major GCC versions are able to produce different looking binaries for sure. This is also the case with LLVM. With different LLVM versions for example the optimizations passes might have changed a bit, or some default threshold values might have changed which affect the optimization decisions, or some other reason why compiler might have taken different turn with the optimization passes.

My best guess to track this down would be if you are able to print intermediate presentation (IR) after each optimization pass in GCC. In LLVM it's possible to see IR after each pass and also print the pass names used. I don't remember the flags anymore from top of my head. Been a long time since last worked with LLVM. IR is of course not the last assembly, but could give you clue what has changed between GCC versions.

Another quite handy tool to use is [Compiler Explorer](https://godbolt.org/). I tried to copy paste your code there but it complains about missing include. You can there quickly test with different GCC and LLVM versions what is the compiled output.

Hope these helps!

**Comment by Hanseltu** [comment]
Hi @Kazhuu, thank you so much for your insightful and helpful comments and suggestions!

Let me continue to investigate more and see what could be a better solution for me.

I just close this issue for now and thank you again for your time!
