### ISSUE TITLE
Test suite to avoid manual testing

### ISSUE THREAD

**Issue by Kazhuu** [Kazhuu/asm2cfg#4]
This repository needs a test suite so we could avoid manual testing with provided reference pdf and asm files.

**Comment by yugr** [comment]
Do you have particular ideas on which testing framework to use and tests to add? I assume existing examples could be used as first step but eventually more fine-grained unit/function-level tests should be added...

**Comment by Kazhuu** [comment]
If I were doing this I would first go with Python testing library to see if that could cover everything. We are testing Python code after all. Choosing between build in [unittest](https://docs.python.org/3/library/unittest.html) or [pytest](https://docs.pytest.org/en/6.2.x/) doesn't really matter to me. I'm more familiar with unittest but have heard good things about pytest. So maybe that could be way to go.

Biggest problems that I can think of that will be hard to test are GDB commands and parameters usage, and standalone mode. I don't think you can diff pdf files. Maybe some other format could be used or something similar that the output could be verified.

Python could be easily used to test inner functions but the interfacing parts I'm open for ideas. Higher level Python tests could execute GDB commands and diff output to verified output and fail if they differ.

One of the PRs you mentioned autotests? Could that cover something like this? I'm not very familiar with that tool.
